### PR TITLE
bmaas - log virtual baremetal console to file

### PR DESCRIPTION
**Pull request by hjensas**
Set up the virtual baremetal nodes created to log to a file.

Inject a libvirt hook that will archive the console log's when a vm is powered off. Logs are archived in two formats, the original log file including ANSI control codes and a _no_ansi_ log with ANSI codes removed.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/726

### CODE REVIEW

**Comment by hjensas** [comment]
recheck

**Comment by hjensas** [comment]
Error is legit - permission issue on logdir:
`Unable to open file: /var/log/bmaas_console_logs/edpm-compute-01_console.log: Permission denied`

```bash
2023-10-19T20:08:21.997119961+00:00 stderr F 2023-10-19 20:08:21.988 1 ERROR ironic.conductor.utils ironic.common.exception.RedfishError: Redfish exception occurred. Error: Reboot failed for node ea400b4a-3618-4657-a745-df6ce51433e2 when setting power state to power on. Error: HTTP POST http://sushy-emulator.apps-crc.testing/redfish/v1/Systems/fbbeeffa-6d97-4204-b8c8-6c7c7b901973/Actions/ComputerSystem.Reset returned code 500. Base.1.0.GeneralError: Error changing power state at libvirt URI "qemu+ssh://sushyemu@192.168.130.1/system?socket=/var/run/libvirt/libvirt-sock": Unable to open file: /var/log/bmaas_console_logs/edpm-compute-01_console.log: Permission denied Extended information: [{'@odata.type': '/redfish/v1/$metadata#Message.1.0.0.Message', 'MessageId': 'Base.1.0.GeneralError'}]
```

**Comment by hjensas** [comment]
recheck

**Comment by cjeanner** [comment]
FYI, we may even test we get those logs in the ci-framework "logs" by adding a depends-on https://github.com/openstack-k8s-operators/install_yamls/pull/592 - or the reverse. The ci-framework patch should work with or without that path anyway.

**Comment by hjensas** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by hjensas** [comment]
so, this works: https://review.rdoproject.org/zuul/build/d09ca59cb1104f11b9c3df1398fb4e8f/log/ci-framework-data/logs/bmaas_console_logs/edpm-compute-01_no_ansi_2023-10-25-09:34:11.log

```
[=3h[=3h[=3h
>>Start PXE over IPv4.
  Station IP address is 192.168.122.59

  Server IP address is 192.168.122.10
  NBP filename is snponly.efi
  NBP filesize is 182880 Bytes
 Downloading NBP file...

  NBP file downloaded successfully.
BdsDxe: loading Boot0001 "UEFI PXEv4 (MAC:525400EAC695)" from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/MAC(525400EAC695,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)
BdsDxe: starting Boot0001 "UEFI PXEv4 (MAC:525400EAC695)" from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/MAC(525400EAC695,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)
iPXE initialising devices...ok



iPXE 1.21.1 (g988d) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE EFI Menu

Press Ctrl-B for the iPXE command line...                                         net0: 52:54:00:ea:c6:95 using SNP on SNP-0000:01:00.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 52:54:00:ea:c6:95)...... ok
net0: 192.168.122.59/255.255.255.0
net0: fe80::5054:ff:feea:c695/64
Next server: 192.168.122.10
Filename: http://192.168.122.10:6180/boot.ipxe
http://192.168.122.10:6180/boot.ipxe... ok
boot.ipxe : 1128 bytes [script]
Attempting to boot from MAC 52-54-00-ea-c6-95
pxelinux.cfg/52-54-00-ea-c6-95... ok
http://192.168.122.10:6180/cf881eba-62d9-4a11-a015-de7d8a51feda/deploy_kernel... ok
http://192.168.122.10:6180/cf881eba-62d9-4a11-a015-de7d8a51feda/deploy_ramdisk... 10%     20%     30%     39%     48%     58%     68%     78%     85%     95%     ok
EFI stub: Loaded initrd from command line option
[    0.000000] Linux version 5.14.0-373.el9.x86_64 (mockbuild@x86-05.stream.rdu2.redhat.com) (gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), GNU ld version 2.35.2-42.el9) #1 SMP PREEMPT_DYNAMIC Thu Oct 5 02:38:42 UTC 2023
[    0.000000] The list of certified hardware and cloud instances for Red Hat Enterprise Linux 9 can be viewed at the Red Hat Ecosystem Catalog, https://catalog.redhat.com.
[    0.000000] Command line: deploy_kernel selinux=0 troubleshoot=0 text nofb nomodeset vga=normal ipa-insecure=1 console=ttyS0 systemd.journald.forward_to_console=yes ipa-debug=1 ipa-api-url=https://192.168.122.10:6385 ipa-global-request-id=req-d68de690-fec2-4d66-aea3-74b02d1bf437 BOOTIF=52:54:00:ea:c6:95 initrd=deploy_ramdisk
```

**Review by rabi — APPROVED** [review]
/lgtm

**Review by steveb — APPROVED** [review]
/lgtm

**Comment by cjeanner** [comment]
/approve
(not sure I'm allowed though)

**Pull request merged**
