### PR TITLE
Switch to use IPAM in EDPM baremetal job

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/382
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/346

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Review by abays — APPROVED** [review]
I tested this from scratch (i.e. completely wiped CRC and started from there) and it succeeded on my second attempt.  The first try failed to provision the BMH, with this error appearing in the Metal3 operator logs:

```
Deploy step deploy.boot_instance failed: Error booting node 198f311a-672e-470a-b9ee-4248fe85bb75 after deploy. OperationalError: (sqlite3.OperationalError) database is locked
```

Not sure what caused it.  Perhaps it was some flakiness in my environment.

/lgtm

**Comment by abays** [comment]
recheck

**Comment by rabi** [comment]
I think the issue is after provisioning. I noticed that we don't deploy metallb when NETWORK_ISOLATION=false, so the DNS LB endpoint is not available and we download some images in the nodes from quay.. I've a patch in ci-framework[1] and would add as Depends-On here.. Hope the the depends-on would work. ELse we've to wait for [1] to merge.

[1] https://github.com/openstack-k8s-operators/ci-framework/pull/346

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
> The first try failed to provision the BMH, with this error appearing in the Metal3 operator logs

@abays Yeah that's because currently ironic uses sqlite as the database and it sometimes ends up in locking issues. I normally delete the ironic pod in `baremetal-operator-system`  and that fixes the issue. I've been thinking about changing to use mariadb which would require TLS to be configured for ironic.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
