### PR TITLE
nmstate-operator: Check deployment status instead of pod status

### PR DESCRIPTION
**Pull request by kajinamit**
... to simplify the query.

This also fixes the hard-coded namespace of NMState CR.

### CODE REVIEW

**Comment by raukadah** [comment]
@kajinamit Thank you for working on this pr. I got the pr link from slack regarding following issue
```
Error from server (InternalError): error when creating "/home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr/crc-74q6p-master-0_nncp.yaml": Internal error occurred: failed calling webhook "nodenetworkconfigurationpolicies-mutate.nmstate.io": failed to call webhook: Post "https://nmstate-webhook.openshift-nmstate.svc:443/nodenetworkconfigurationpolicies-mutate?timeout=10s": no endpoints available for service "nmstate-webhook"
gmake: *** [Makefile:1741: nncp] Error 1
```
We are seeing it in frequently in baremetal jobs[[1].](https://logserver.rdoproject.org/21/421/3addf383b2c2c85444e1b196290005cddb9183bd/github-check/ci-framework-crc-podified-edpm-deployment/091dc55/ci-framework-data/logs/ci_make_002_run_openstack.log) and [[2].](https://logserver.rdoproject.org/54/454/d722c4e3ec7fa05198465d18c4cb3758aa1508e6/github-check/ci-framework-crc-podified-edpm-baremetal/9be70d1/ci-framework-data/logs/ci_make_002_run_openstack.log)

Can we get this pr merged? It will help to mitigate the above issue. Thank you :-)

**Comment by abays** [comment]
recheck

**Comment by kajinamit** [comment]
the failure in galera-deployment job indicates that webhook was not ready.

```
Internal error occurred: failed calling webhook \"mopenstackcontrolplane.kb.io\": failed to call webhook: Post \"https://openstack-operator-controller-manager-service.openstack-operators.svc:443/mutate-core-openstack-org-v1beta1-openstackcontrolplane?timeout=10s\": dial tcp 10.217.0.114:9443: connect: connection refused
```

I've submitted https://github.com/openstack-k8s-operators/openstack-operator/pull/434 (I've also submitted the same to the other operators as well) to avoid that error.

**Comment by abays** [comment]
> the failure in galera-deployment job indicates that webhook was not ready.
> 
> ```
> Internal error occurred: failed calling webhook \"mopenstackcontrolplane.kb.io\": failed to call webhook: Post \"https://openstack-operator-controller-manager-service.openstack-operators.svc:443/mutate-core-openstack-org-v1beta1-openstackcontrolplane?timeout=10s\": dial tcp 10.217.0.114:9443: connect: connection refused
> ```
> 
> I've submitted [openstack-k8s-operators/openstack-operator#434](https://github.com/openstack-k8s-operators/openstack-operator/pull/434) (I've also submitted the same to the other operators as well) to avoid that error.

Yes, I think we have one or two of this similar patches already merged and they seem to be working (or at least to have had no ill effects).  Let's roll them out across the operators and see how they might improve things.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
