### PR TITLE
Switch to main branch

### PR DESCRIPTION
**Pull request by slawqo**
We've renamed the development branch of neutron-operator to main. This updates the branch used for installation accordingly.

### CODE REVIEW

**Review by fmount — APPROVED** [review]

**Comment by fmount** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by slawqo** [comment]
recheck

**Comment by slawqo** [comment]
recheck

**Comment by slawqo** [comment]
Already fixed in #270

**Pull request closed without merging**
