### PR TITLE
Only add second node when NODE_COUNT=2

### PR DESCRIPTION
**Pull request by Sandeepyadav93**
By default we create dataplane.yaml for 2 nodes,
With this commit we only add second node when
NODE_COUNT=2.

### CODE REVIEW

**Review by rabi — APPROVED** [review]
/lgtm

**Comment by Sandeepyadav93** [comment]
recheck

Checking if issue is consistent

**Comment by raukadah** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Pull request merged**
