### PR TITLE
Adoption: remove podman pin

### PR DESCRIPTION
**Pull request by jistr**
Resolves: [OSPRH-8539](https://issues.redhat.com//browse/OSPRH-8539)

### CODE REVIEW

**Comment by bogdando** [comment]
let's check this in testproject for adoption jobs to not fail with this change.
It might be that we still want the pinning in upstream CI as we are using RDO

**Comment by jistr** [comment]
Marking as ready to review. I tested this on periodic job, with testproject both upstream and downstream. All green. (More details in the Jira card.)

**Review by fao89 — APPROVED** [review]

**Pull request merged**
