### PR TITLE
[dev-preview2] pin opm to v1.30.0

### PR DESCRIPTION
**Pull request by stuggi**
(cherry picked from commit aea99f2b0e02707e733dc4a56216db3728d4d09c)

### CODE REVIEW

**Comment by bshewale** [comment]
+1 thanks :)

**Comment by cescgina** [comment]
@stuggi maybe I'm getting it wrong, but shouldn't this PR be against `openstack-k8s-operators:dev-preview2` instead of `openstack-k8s-operators:main` (at least that what it seems from the message at the top of the page):
```
stuggi wants to merge 1 commit into openstack-k8s-operators:main stuggi:pin_opm_dev-review2
```

**Comment by stuggi** [comment]
> @stuggi maybe I'm getting it wrong, but shouldn't this PR be against `openstack-k8s-operators:dev-preview2` instead of `openstack-k8s-operators:main` (at least that what it seems from the message at the top of the page):
> 
> ```
> stuggi wants to merge 1 commit into openstack-k8s-operators:main stuggi:pin_opm_dev-review2
> ```

yes, created the PR wrong. thanks for the pointer

**Comment by stuggi** [comment]
https://github.com/openstack-k8s-operators/install_yamls/pull/613

**Pull request closed without merging**
