### PR TITLE
Fix indenting that breaks nodes > 1

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/429

### CODE REVIEW

**Review by bshephar — APPROVED** [review]

**Comment by abays** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
> @rabi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/install-yamls-deploy 	[eb4fc14](https://github.com/openstack-k8s-operators/install_yamls/commit/eb4fc144b8aa3b1c9ff859f06e3242a97d71de78) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_install_yamls/545/pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy/1705139044070985728) 	false 	`/test install-yamls-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=install_yamls&pr=545). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:rabi).

I know this is not related to this PR, but this is why `install-yamls-deploy` failed.  The control plane could not successfully deploy because the Ceilometer deployment hit this:

```
Warning  Failed          24m (x3 over 25m)    kubelet            Failed to pull image "quay.io/infrawatch/sg-core@sha256:f277dbed6ec445a3b4707b8d3dd71d871feebb8e92ec9995d49e003c6069931d": rpc error: code = Unknown desc = reading manifest sha256:f277dbed6ec445a3b4707b8d3dd71d871feebb8e92ec9995d49e003c6069931d in quay.io/infrawatch/sg-core: manifest unknown: manifest unknown
```

I checked quay, and indeed that sha256 does not exist for `infrawatch/sg-core`.

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
recheck

jobs fixed

**Comment by rabi** [comment]
Now the baremetal job is broken with https://github.com/openstack-k8s-operators/edpm-ansible/pull/358.  Testing with https://github.com/openstack-k8s-operators/dataplane-operator/pull/429

**Comment by rabi** [comment]
recheck

**Pull request merged**
