### PR TITLE
Add ironic kuttl commands to Makefile

### PR DESCRIPTION
**Pull request by jparoly**
Started to build scaffolding for ironic operator kuttle tests.

### CODE REVIEW

**Comment by abays** [comment]
Are there actual KUTTL tests in the Ironic operator yet?  I don't see any at first glance.

**Comment by jparoly** [comment]
Not yet, working on it.  I can mark this as draft for now.

**Comment by jparoly** [comment]
> Not yet, working on it. I can mark this as draft for now.

Actually I don't see the option to mark it as draft. What is the correct process?

**Comment by jparoly** [comment]
moving to a fork instead

**Pull request closed without merging**
