### PR TITLE
[edpm_deploy_instance] Update public subnet allocation pool

### PR DESCRIPTION
**Pull request by karelyatin**
Current allocation was quite low, increase it to also match what being done with os_net_setup[1].

Also enabled dhcp and update subnet name.

[1] https://github.com/openstack-k8s-operators/ci-framework/blob/main/roles/os_net_setup/defaults/main.yml

### CODE REVIEW

**Comment by karelyatin** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by karelyatin** [comment]
recheck unrelated failure, if it fails again can override

**Comment by karelyatin** [comment]
@abays can we get this in, ci green now

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
