### PR TITLE
Switch hard-coded namespace to a variable for 'make ceph'

### PR DESCRIPTION
**Pull request by fultonj**
The gen-ceph-kustomize.sh script which, is run when `make ceph` is run, accepts a namespace parameter but still has the 'openstack' namespace hard-coded in some spots. Replace them with the namespace variable.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/498

### CODE REVIEW

**Comment by fultonj** [comment]
This PR is made in response to https://github.com/openstack-k8s-operators/manila-operator/pull/122 which timed out waiting the cluster to be up. I assume this is because the kuttl test in the manila-kuttl-tests namespace could not make contact with the ceph pod in the opentack namespace.

**Review by abays — APPROVED** [review]
/lgtm

**Review by fmount — APPROVED** [review]
Makes sense, especially w/ kuttl tests running in an arbitrary namespace. Without this change we're not able to interact w/ Ceph that will be deployed in `openstack` namespace.

**Comment by fmount** [comment]
recheck

**Comment by fmount** [comment]
recheck

**Comment by fmount** [comment]
recheck

**Comment by fmount** [comment]
recheck

**Pull request merged**
