### PR TITLE
Fix standalone target script generation

### PR DESCRIPTION
**Pull request by booxter**
The script was not updated, and the result contained undesired backquotes around CEPH_ARGS.

### CODE REVIEW

**Comment by booxter** [comment]
recheck

"error: You must be logged in to the server (Unauthorized)" is unrelated to CEPH_ARGS changes

**Comment by jpodivin** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Pull request merged**
