### PR TITLE
Install baremetal for dataplane kuttl tests

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
+1

Dataplane kuttl test are failing currently: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/279/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1678718358272348160/artifacts/dataplane-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

I was able to replicate the issue and saw below in logs

~~~
{"level":"error","ts":"2023-07-11T15:48:51Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"OpenStackBaremetalSet.baremetal.openstack.org","error":"no matches for kind \"OpenStackBaremetalSet\" in version \"baremetal.openstack.org/v1beta1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/source/source.go:136"
~~~

Kuttl test passes with this PR locally

**Comment by fao89** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by slagle** [comment]
recheck

**Comment by rabi** [comment]
https://github.com/openstack-k8s-operators/install_yamls/pull/394 was already there.

**Pull request merged**
