### PR TITLE
Use kustomize to modify the sample CRs

### PR DESCRIPTION
**Pull request by rabi**
Using the samples would help not to put everything inline. Though ansibleVars have to replaced as a string atm.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
@Sandeepyadav93 @abays this is ready (other than some jobs failing with the swift issue), once we get this in we can put a PR to change the sample in dataplane-operator to use IPAM/DNS.

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
