### PR TITLE
Update EDPM ansibleVars

### PR DESCRIPTION
**Pull request by fao89**
ref: https://github.com/openstack-k8s-operators/dataplane-operator/pull/319

Only patching what isn't on the original samples

### CODE REVIEW

**Comment by fao89** [comment]
@rabi feel free to cherrypick/close this PR

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by raukadah** [comment]
Similar pr https://github.com/openstack-k8s-operators/install_yamls/pull/442 is also opened to make changes for both EDPM and baremetal kustomization.

**Comment by fao89** [comment]
closing in favor of https://github.com/openstack-k8s-operators/install_yamls/pull/442

**Pull request closed without merging**
