### PR TITLE
Generate Octavia amphora server CA secret

### PR DESCRIPTION
**Pull request by weinimo**
This is required for https://github.com/openstack-k8s-operators/octavia-operator/pull/207/

### CODE REVIEW

**Comment by weinimo** [comment]
recheck not sure why horizon did not come up

**Comment by abays** [comment]
recheck

Manila was the culprit this time:

```
FAILED - RETRYING: [localhost]: wait for Manila to start up (1 retries left).
```

**Comment by weinimo** [comment]
recheck RETRY_LIMIT?!

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
