### PR TITLE
Fix edpm_baremetal_deploy registry and tag vars

### PR DESCRIPTION
**Pull request by abays**
Without these included in the `make edpm_baremetal_deploy` target, one of the AnsibleEE jobs fails like so:

```
TASK [osp.edpm.edpm_ovn : Run neutron_metadata_agent container] ****************
task path: /usr/share/ansible/collections/ansible_collections/osp/edpm/roles/edpm_ovn/tasks/configure.yml:73
Tuesday 08 August 2023  15:02:15 +0000 (0:00:00.596)       0:00:22.987 ******** 
fatal: [edpm-compute-0]: FAILED! => {"changed": true, "cmd": "podman run --detach --name neutron_metadata_config /openstack-neutron-metadata-agent-ovn: sleep infinity\n", "delta": "0:00:00.039690", "end": "2023-08-08 15:02:16.490934", "msg": "non-zero return code", "rc": 125, "start": "2023-08-08 15:02:16.451244", "stderr": "Error: invalid reference format", "stderr_lines": ["Error: invalid reference format"], "stdout": "", "stdout_lines": []}
```

This is also fixed via https://github.com/openstack-k8s-operators/install_yamls/pull/460, but that PR is lingering and we need to get this fix in so that the baremetal Zuul job starts passing.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by steveb — APPROVED** [review]
/lgtm

**Comment by rabi** [comment]
Yeah we can merge this to fix that make target after rebase.

**Comment by abays** [comment]
It looks like some other PR was merged and also introduced these changes

**Pull request closed without merging**
