### PR TITLE
validate OCP marketplace

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
https://github.com/openstack-k8s-operators/install_yamls/pull/812#issuecomment-2074167584

**Comment by rabi** [comment]
I think this won't be tested in CI atm as we're using OCP 4.14, but would be needed for local deploys with crc 2.34(OCP 4.15)

**Comment by stuggi** [comment]
> I think this won't be tested in CI atm as we're using OCP 4.14, but would be needed for local deploys with crc 2.34(OCP 4.15)

yes, only parts of it were running, but there was no need to fix the marketplace resources:

```
bash scripts/validate-marketplace.sh
+ '[' -z 300s ']'
+ OPERATOR_NAMESPACE=openshift-marketplace
+ oc get pods -n openshift-marketplace
+ grep CrashLoopBackOff
+ '[' 1 -eq 0 ']'
+ OPERATORS='openshift-cert-manager-operator kubernetes-nmstate-operator metallb-operator'
+ for operator in $OPERATORS
+ n=0
+ retries=20
+ true
+ grep openshift-cert-manager-operator
+ oc get packagemanifests -n openshift-marketplace
openshift-cert-manager-operator                    Red Hat Operators     16m
+ '[' 0 -eq 0 ']'
+ break
+ for operator in $OPERATORS
+ n=0
+ retries=20
+ true
+ oc get packagemanifests -n openshift-marketplace
+ grep kubernetes-nmstate-operator
kubernetes-nmstate-operator                        Red Hat Operators     16m
+ '[' 0 -eq 0 ']'
+ break
+ for operator in $OPERATORS
+ n=0
+ retries=20
+ true
+ oc get packagemanifests -n openshift-marketplace
+ grep metallb-operator
metallb-operator                                   Red Hat Operators     16m
+ '[' 0 -eq 0 ']'
+ break
```

**Pull request merged**
