### PR TITLE
Allow running glance kuttl test in any namespace

### PR DESCRIPTION
**Pull request by vhariria**

### CODE REVIEW

**Review by cescgina — COMMENTED** [review]
lgtm

**Comment by abays** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
the `install-yamls-crc-podified-galera-deployment` job seems to fail consistently due to missing openstackclient, we probably do not need to block this PR that's only related to kuttl on it:
```
\"Error from server (NotFound): pods \\\"openstackclient\\\" not found\\nError from server (NotFound): pods \\\"openstackclient\\\" not found\"
```

**Comment by abays** [comment]
> the `install-yamls-crc-podified-galera-deployment` job seems to fail consistently due to missing openstackclient, we probably do not need to block this PR that's only related to kuttl on it:
> 
> ```
> \"Error from server (NotFound): pods \\\"openstackclient\\\" not found\\nError from server (NotFound): pods \\\"openstackclient\\\" not found\"
> ```

https://github.com/openstack-k8s-operators/openstack-operator/pull/401 merged to fix this problem

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
