### PR TITLE
Fix pre-commit issues

### PR DESCRIPTION
**Pull request by raukadah**
In order to enable prow on install_yamls repo. We need to fix pre-commit issues discovered on this pr
https://github.com/openshift/release/pull/36396.

This patch fixes the same.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by Sandeepyadav93** [comment]
Thanks, Chandan

Apart from these failures I am seeing more issues locally:

~~~
Ansible-lint.............................................................Failed
- hook id: ansible-lint
- duration: 2.09s
- exit code: 2

INFO     Set ANSIBLE_LIBRARY=/home/sandeepyadav/.cache/ansible-compat/8ef565/modules:/home/sandeepyadav/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/home/sandeepyadav/.cache/ansible-compat/8ef565/collections:/home/sandeepyadav/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/home/sandeepyadav/.cache/ansible-compat/8ef565/roles:/home/sandeepyadav/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Discovered files to lint using: git -c safe.directory=/tmp/install_yamls ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git -c safe.directory=/tmp/install_yamls ls-files --deleted -z
INFO     Discovered files to lint using: git -c safe.directory=/tmp/install_yamls ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git -c safe.directory=/tmp/install_yamls ls-files --deleted -z
INFO     Executing syntax check on ci/playbooks/collect_logs.yaml (0.45s)
INFO     Executing syntax check on ci/playbooks/deploy_podified_openstack.yaml (0.46s)
WARNING  Listing 17 violation(s) that are fatal
ci/playbooks/collect_logs.yaml:2: name[play]: All plays should be named. (warning)
ci/playbooks/collect_logs.yaml:5: fqcn[action-core]: Use FQCN for builtin module actions (file).
ci/playbooks/collect_logs.yaml:11: name[play]: All plays should be named. (warning)
ci/playbooks/collect_logs.yaml:14: fqcn[action-core]: Use FQCN for builtin module actions (file).
ci/playbooks/collect_logs.yaml:20: ignore-errors: Use failed_when and specify error conditions instead of using ignore_errors. (warning)
ci/playbooks/collect_logs.yaml:55: name[play]: All plays should be named. (warning)
ci/playbooks/collect_logs.yaml:58: fqcn[action-core]: Use FQCN for builtin module actions (include_role).
ci/playbooks/collect_logs.yaml:58: name[template]: Jinja templates should only be at the end of 'name'
ci/playbooks/deploy_podified_openstack.yaml:6: name[play]: All plays should be named. (warning)
ci/playbooks/deploy_podified_openstack.yaml:10: fqcn[action-core]: Use FQCN for builtin module actions (include_role).
ci/playbooks/deploy_podified_openstack.yaml:15: no-changed-when: Commands should not change things if nothing needs doing.
ci/playbooks/deploy_podified_openstack.yaml:18: no-changed-when: Commands should not change things if nothing needs doing.
ci/playbooks/deploy_podified_openstack.yaml:18: risky-shell-pipe: Shells that use pipes should set the pipefail option.
ci/playbooks/deploy_podified_openstack.yaml:35: no-changed-when: Commands should not change things if nothing needs doing.
ci/playbooks/deploy_podified_openstack.yaml:43: no-changed-when: Commands should not change things if nothing needs doing.
ci/playbooks/deploy_podified_openstack.yaml:43: risky-shell-pipe: Shells that use pipes should set the pipefail option.
ci/playbooks/deploy_podified_openstack.yaml:51: no-changed-when: Commands should not change things if nothing needs doing.
You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental
  - fqcn[action-core]  # Use FQCN for builtin actions.
  - name[template]  # Rule for checking task and play names.
  - no-changed-when  # Commands should not change things if nothing needs doing.
  - risky-shell-pipe  # Shells that use pipes should set the pipefail option.

                           Rule Violation Summary                            
 count tag               profile    rule associated tags                     
     4 name[play]        basic      idiom (warning)                          
     1 name[template]    moderate   idiom                                    
     2 risky-shell-pipe  safety     command-shell                            
     1 ignore-errors     shared     unpredictability, experimental (warning) 
     5 no-changed-when   shared     command-shell, idempotency               
     4 fqcn[action-core] production formatting                               

Failed after min profile: 12 failure(s), 5 warning(s) on 46 files.

bashate..................................................................Failed
- hook id: bashate
- exit code: 1

devsetup/scripts/crc-setup.sh:53:1: E003 Indent not multiple of 4
1 bashate error(s) found
~~~

bashate error is noticed in CI as well: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36396/rehearse-36396-pull-ci-openstack-k8s-operators-install_yamls-master-precommit-check/1642759263900143616#1:build-log.txt%3A129

**Comment by raukadah** [comment]
Thank you @Sandeepyadav93 for highlighting those issue. I fixed it now.

**Comment by Sandeepyadav93** [comment]
Thanks Chandan, looks good now. Tests are passing locally with the updates.

**Review by gibizer — APPROVED** [review]
looks good

**Pull request merged**
