### PR TITLE
Limit affinity of local storage pv

### PR DESCRIPTION
**Pull request by dciabrin**
When a pod claims a persistent volume that is configured to store data locally to a worker node, it should not be allowed to restart on another worker node or it will not see the expected data.

Change the way we generate the pv to only allow a pod to restart locally once it claimed a pv, by generating pv for each worker node in the cluster.

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
+1

I have tested your PR with 3 node setup in CI using a workaround https://github.com/openshift/release/pull/41636/files#diff-fc06cf4a5ff800bdf9ec8e6ae5ed10a2776e761df803f7a9f83ba078804d4817R65 , 

job is green with this PR: 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41636/rehearse-41636-pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1684417326184665088

another run:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41636/rehearse-41636-pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1684537535797137408

**Comment by viroel** [comment]
+1, CI is passing with this. Thanks @dciabrin and @Sandeepyadav93

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
