### PR TITLE
Fix hostnamemap generation for HCI tripleo

### PR DESCRIPTION
**Pull request by bogdando**
Follow-up to fix HCI regression introduced by https://github.com/openstack-k8s-operators/install_yamls/pull/826

### CODE REVIEW

**Comment by bogdando** [comment]
testproject https://review.rdoproject.org/r/c/testproject/+/54362

**Review by marios — COMMENTED** [review]
i think lgtm from visual inspection but waiting on the test run to sanity check https://review.rdoproject.org/r/c/testproject/+/54362/1/.zuul.yaml

i don't think this affects the downstream networker job at least from inspection i can't spot something

**Comment by viroel** [comment]
test results looks good:
https://review.rdoproject.org/r/c/testproject/+/54362/1#message-68618fb8be95984782881bdb47f759c1f4a5b0a6

**Review by fmount — COMMENTED** [review]
/lgtm

**Comment by viroel** [comment]
/approve

thanks, this will unblock adption-multinode jobs

**Pull request merged**
