### PR TITLE
Initialise NodeSet spec/env

### PR DESCRIPTION
**Pull request by bshephar**
This change initialises the NodeSet /spec/env section before trying to append values to it

### CODE REVIEW

**Comment by fmount** [comment]
@bshephar note that the `data-plane-adoption` job will fail until [1] lands (/cc @cescgina)

[1] https://github.com/openstack-k8s-operators/data-plane-adoption/pull/221

**Comment by fmount** [comment]
recheck

**Comment by abays** [comment]
recheck

Trying again, but baremetal job failure looks like it might be this:

```
"Error from server: error when creating \"STDIN\": admission webhook \"mopenstackdataplanenodeset.kb.io\" denied the request: json: cannot unmarshal object into Go struct field OpenStackDataPlaneNodeSetSpec.spec.env of type []v1.EnvVar"
```

**Comment by bshephar** [comment]
Hmm, seems fine:
https://review.rdoproject.org/zuul/build/c4e59e3a1af44b46b38ea9577f58ae47/log/ci-framework-data/artifacts/manifests/openstack/dataplane/cr/dataplane_v1beta1_openstackdataplanenodeset_baremetal_with_ipam.yaml#6-8

Couple of errors in the dataplane-operator but then it sees the request for the NodeSet:
https://review.rdoproject.org/zuul/build/c4e59e3a1af44b46b38ea9577f58ae47/log/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-206e6f463855943ce5f128d1731718c7a7e0faf5bb2cc0fda0ddeb567abeb18d/namespaces/openstack-operators/pods/dataplane-operator-controller-manager-55f88d876c-49q7b/logs/manager.log#28-31

But there doesn't appear to be a NodeSet CR registered in the cluster:
https://logserver.rdoproject.org/68/668/3e02f1597a1f6b76a7d0fb4d380e5cc775a86512/github-check/install-yamls-crc-podified-edpm-baremetal/c4e59e3/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-206e6f463855943ce5f128d1731718c7a7e0faf5bb2cc0fda0ddeb567abeb18d/namespaces/openstack/crs/

**Comment by bshephar** [comment]
Ah yeah, I see the same error again in the job-output.txt:
```
admission webhook \"mopenstackdataplanenodeset.kb.io\" denied the request: json: cannot unmarshal object into Go struct field OpenStackDataPlaneNodeSetSpec.spec.env of type []v1.EnvVar
```

**Comment by bshephar** [comment]
Let's try completely removing it and if we need to modify this, we can do it via ci-framework.

**Pull request closed without merging**
