### PR TITLE
Enable NETWORK_ISOLATION with baremetal provisioning

### PR DESCRIPTION
**Pull request by rabi**
Now we can use the same interface for both provisioning and other networks.

Also cleans up some redundant targets.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/363

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
