### PR TITLE
Fixing Keystone KUTTL Tests

### PR DESCRIPTION
**Pull request by mauricioharley**
Necessary to make Keystone KUTTL tests to run.

### CODE REVIEW

**Comment by abays** [comment]
For further clarification, this allows `keystone_kuttl` to work with the upcoming https://github.com/openstack-k8s-operators/keystone-operator/pull/325.

**Comment by abays** [comment]
recheck

**Comment by mauricioharley** [comment]
recheck

**Comment by abays** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Pull request merged**
