### PR TITLE
Add telemetry services to wallaby deployment

### PR DESCRIPTION
**Pull request by yadneshk**

### CODE REVIEW

**Comment by yadneshk** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by yadneshk** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

**Review by fao89 — COMMENTED** [review]
```
2024-03-01 07:33:14,123 p=47059 u=root n=ansible | 2024-03-01 07:33:14.119361 | fa163e27-34a0-bc54-90b8-0000000047d8 |      FATAL | Run init bundle puppet on the host for cinder_backup | standalone | error={"changed": false, "cmd": "puppet apply  --detailed-exitcodes --summarize --color=false --modulepath '/etc/puppet/modules:/opt/stack/puppet-modules:/usr/share/openstack-puppet/modules' --tags 'pacemaker::resource::bundle,pacemaker::property,pacemaker::resource::ip,pacemaker::resource::ocf,pacemaker::constraint::order,pacemaker::constraint::colocation' -e 'include ::tripleo::profile::base::pacemaker; include ::tripleo::profile::pacemaker::cinder::backup_bundle'\n", "delta": "0:04:28.691483", "end": "2024-03-01 07:33:14.078959", "failed_when_result": true, "msg": "non-zero return code", "rc": 6, "start": "2024-03-01 07:28:45.387476", "stderr": "Warning: /etc/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5\n   (file: /etc/puppet/hiera.yaml)\nWarning: Undefined variable '::deploy_config_name'; \n   (file & line not available)\nWarning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://puppet.com/docs/puppet/7.10/deprecated_language.html\n   (file & line not available)\nWarning: Scope(Class[Cinder]): The database_connection parameter is deprecated and will be \\\nremoved in a future realse. Use cinder::db::database_connection instead\nWarning: Unknown variable: 'cinder::api::keymgr_backend'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 455, column: 31)\nWarning: Unknown variable: 'cinder::api::keymgr_encryption_api_url'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 456, column: 42)\nWarning: Unknown variable: 'cinder::api::keymgr_encryption_auth_url'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 458, column: 43)\nWarning: Unknown variable: 'ensure'. (file: /etc/puppet/modules/cinder/manifests/backup.pp, line: 94, column: 18)\nDeprecation Warning: This command is deprecated and will be removed. Please use 'pcs property config' instead.\nDeprecation Warning: This command is deprecated and will be removed. Please use 'pcs constraint config' instead.\nError: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20240301-171368-id3kis resource bundle create openstack-cinder-backup container podman image=cluster.common.tag/cinder-backup:pcmklatest replicas=1 options=\"--ipc=host --privileged=true --user=root --log-driver=k8s-file --log-opt path=/var/log/containers/stdouts/openstack-cinder-backup.log -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\" run-command=\"/bin/bash /usr/local/bin/kolla_start\" network=host storage-map id=cinder-backup-etc-hosts source-dir=/etc/hosts target-dir=/etc/hosts options=ro storage-map id=cinder-backup-etc-localtime source-dir=/etc/localtime target-dir=/etc/localtime options=ro storage-map id=cinder-backup-etc-pki-ca-trust-extracted source-dir=/etc/pki/ca-trust/extracted target-dir=/etc/pki/ca-trust/extracted options=ro storage-map id=cinder-backup-etc-pki-ca-trust-source-anchors source-dir=/etc/pki/ca-trust/source/anchors target-dir=/etc/pki/ca-trust/source/anchors options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.crt source-dir=/etc/pki/tls/certs/ca-bundle.crt target-dir=/etc/pki/tls/certs/ca-bundle.crt options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.trust.crt source-dir=/etc/pki/tls/certs/ca-bundle.trust.crt target-dir=/etc/pki/tls/certs/ca-bundle.trust.crt options=ro storage-map id=cinder-backup-etc-pki-tls-cert.pem source-dir=/etc/pki/tls/cert.pem target-dir=/etc/pki/tls/cert.pem options=ro storage-map id=cinder-backup-dev-log source-dir=/dev/log target-dir=/dev/log options=rw storage-map id=cinder-backup-etc-puppet source-dir=/etc/puppet target-dir=/etc/puppet options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-cinder source-dir=/var/lib/config-data/puppet-generated/cinder target-dir=/var/lib/kolla/config_files/src options=ro storage-map id=cinder-backup-var-log-containers-cinder source-dir=/var/log/containers/cinder target-dir=/var/log/cinder options=z storage-map id=cinder-backup-var-lib-kolla-config_files-cinder_backup.json source-dir=/var/lib/kolla/config_files/cinder_backup.json target-dir=/var/lib/kolla/config_files/config.json options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-iscsid-etc-iscsi source-dir=/var/lib/config-data/puppet-generated/iscsid/etc/iscsi target-dir=/var/lib/kolla/config_files/src-iscsid options=ro storage-map id=cinder-backup-var-lib-tripleo-config-ceph source-dir=/var/lib/tripleo-config/ceph target-dir=/var/lib/kolla/config_files/src-ceph options=z storage-map id=cinder-backup-dev source-dir=/dev target-dir=/dev options=rw storage-map id=cinder-backup-run source-dir=/run target-dir=/run options=rw storage-map id=cinder-backup-sys source-dir=/sys target-dir=/sys options=rw storage-map id=cinder-backup-lib-modules source-dir=/lib/modules target-dir=/lib/modules options=ro storage-map id=cinder-backup-var-lib-cinder source-dir=/var/lib/cinder target-dir=/var/lib/cinder options=z storage-map id=cinder-backup-var-lib-iscsi source-dir=/var/lib/iscsi target-dir=/var/lib/iscsi options=z --disabled failed: . Too many tries\nError: /Stage[main]/Tripleo::Profile::Pacemaker::Cinder::Backup_bundle/Pacemaker::Resource::Bundle[openstack-cinder-backup]/Pcmk_bundle[openstack-cinder-backup]/ensure: change from 'absent' to 'present' failed: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20240301-171368-id3kis resource bundle create openstack-cinder-backup container podman image=cluster.common.tag/cinder-backup:pcmklatest replicas=1 options=\"--ipc=host --privileged=true --user=root --log-driver=k8s-file --log-opt path=/var/log/containers/stdouts/openstack-cinder-backup.log -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\" run-command=\"/bin/bash /usr/local/bin/kolla_start\" network=host storage-map id=cinder-backup-etc-hosts source-dir=/etc/hosts target-dir=/etc/hosts options=ro storage-map id=cinder-backup-etc-localtime source-dir=/etc/localtime target-dir=/etc/localtime options=ro storage-map id=cinder-backup-etc-pki-ca-trust-extracted source-dir=/etc/pki/ca-trust/extracted target-dir=/etc/pki/ca-trust/extracted options=ro storage-map id=cinder-backup-etc-pki-ca-trust-source-anchors source-dir=/etc/pki/ca-trust/source/anchors target-dir=/etc/pki/ca-trust/source/anchors options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.crt source-dir=/etc/pki/tls/certs/ca-bundle.crt target-dir=/etc/pki/tls/certs/ca-bundle.crt options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.trust.crt source-dir=/etc/pki/tls/certs/ca-bundle.trust.crt target-dir=/etc/pki/tls/certs/ca-bundle.trust.crt options=ro storage-map id=cinder-backup-etc-pki-tls-cert.pem source-dir=/etc/pki/tls/cert.pem target-dir=/etc/pki/tls/cert.pem options=ro storage-map id=cinder-backup-dev-log source-dir=/dev/log target-dir=/dev/log options=rw storage-map id=cinder-backup-etc-puppet source-dir=/etc/puppet target-dir=/etc/puppet options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-cinder source-dir=/var/lib/config-data/puppet-generated/cinder target-dir=/var/lib/kolla/config_files/src options=ro storage-map id=cinder-backup-var-log-containers-cinder source-dir=/var/log/containers/cinder target-dir=/var/log/cinder options=z storage-map id=cinder-backup-var-lib-kolla-config_files-cinder_backup.json source-dir=/var/lib/kolla/config_files/cinder_backup.json target-dir=/var/lib/kolla/config_files/config.json options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-iscsid-etc-iscsi source-dir=/var/lib/config-data/puppet-generated/iscsid/etc/iscsi target-dir=/var/lib/kolla/config_files/src-iscsid options=ro storage-map id=cinder-backup-var-lib-tripleo-config-ceph source-dir=/var/lib/tripleo-config/ceph target-dir=/var/lib/kolla/config_files/src-ceph options=z storage-map id=cinder-backup-dev source-dir=/dev target-dir=/dev options=rw storage-map id=cinder-backup-run source-dir=/run target-dir=/run options=rw storage-map id=cinder-backup-sys source-dir=/sys target-dir=/sys options=rw storage-map id=cinder-backup-lib-modules source-dir=/lib/modules target-dir=/lib/modules options=ro storage-map id=cinder-backup-var-lib-cinder source-dir=/var/lib/cinder target-dir=/var/lib/cinder options=z storage-map id=cinder-backup-var-lib-iscsi source-dir=/var/lib/iscsi target-dir=/var/lib/iscsi options=z --disabled failed: . Too many tries", "stderr_lines": ["Warning: /etc/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5", "   (file: /etc/puppet/hiera.yaml)", "Warning: Undefined variable '::deploy_config_name'; ", "   (file & line not available)", "Warning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://puppet.com/docs/puppet/7.10/deprecated_language.html", "   (file & line not available)", "Warning: Scope(Class[Cinder]): The database_connection parameter is deprecated and will be \\", "removed in a future realse. Use cinder::db::database_connection instead", "Warning: Unknown variable: 'cinder::api::keymgr_backend'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 455, column: 31)", "Warning: Unknown variable: 'cinder::api::keymgr_encryption_api_url'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 456, column: 42)", "Warning: Unknown variable: 'cinder::api::keymgr_encryption_auth_url'. (file: /etc/puppet/modules/cinder/manifests/init.pp, line: 458, column: 43)", "Warning: Unknown variable: 'ensure'. (file: /etc/puppet/modules/cinder/manifests/backup.pp, line: 94, column: 18)", "Deprecation Warning: This command is deprecated and will be removed. Please use 'pcs property config' instead.", "Deprecation Warning: This command is deprecated and will be removed. Please use 'pcs constraint config' instead.", "Error: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20240301-171368-id3kis resource bundle create openstack-cinder-backup container podman image=cluster.common.tag/cinder-backup:pcmklatest replicas=1 options=\"--ipc=host --privileged=true --user=root --log-driver=k8s-file --log-opt path=/var/log/containers/stdouts/openstack-cinder-backup.log -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\" run-command=\"/bin/bash /usr/local/bin/kolla_start\" network=host storage-map id=cinder-backup-etc-hosts source-dir=/etc/hosts target-dir=/etc/hosts options=ro storage-map id=cinder-backup-etc-localtime source-dir=/etc/localtime target-dir=/etc/localtime options=ro storage-map id=cinder-backup-etc-pki-ca-trust-extracted source-dir=/etc/pki/ca-trust/extracted target-dir=/etc/pki/ca-trust/extracted options=ro storage-map id=cinder-backup-etc-pki-ca-trust-source-anchors source-dir=/etc/pki/ca-trust/source/anchors target-dir=/etc/pki/ca-trust/source/anchors options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.crt source-dir=/etc/pki/tls/certs/ca-bundle.crt target-dir=/etc/pki/tls/certs/ca-bundle.crt options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.trust.crt source-dir=/etc/pki/tls/certs/ca-bundle.trust.crt target-dir=/etc/pki/tls/certs/ca-bundle.trust.crt options=ro storage-map id=cinder-backup-etc-pki-tls-cert.pem source-dir=/etc/pki/tls/cert.pem target-dir=/etc/pki/tls/cert.pem options=ro storage-map id=cinder-backup-dev-log source-dir=/dev/log target-dir=/dev/log options=rw storage-map id=cinder-backup-etc-puppet source-dir=/etc/puppet target-dir=/etc/puppet options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-cinder source-dir=/var/lib/config-data/puppet-generated/cinder target-dir=/var/lib/kolla/config_files/src options=ro storage-map id=cinder-backup-var-log-containers-cinder source-dir=/var/log/containers/cinder target-dir=/var/log/cinder options=z storage-map id=cinder-backup-var-lib-kolla-config_files-cinder_backup.json source-dir=/var/lib/kolla/config_files/cinder_backup.json target-dir=/var/lib/kolla/config_files/config.json options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-iscsid-etc-iscsi source-dir=/var/lib/config-data/puppet-generated/iscsid/etc/iscsi target-dir=/var/lib/kolla/config_files/src-iscsid options=ro storage-map id=cinder-backup-var-lib-tripleo-config-ceph source-dir=/var/lib/tripleo-config/ceph target-dir=/var/lib/kolla/config_files/src-ceph options=z storage-map id=cinder-backup-dev source-dir=/dev target-dir=/dev options=rw storage-map id=cinder-backup-run source-dir=/run target-dir=/run options=rw storage-map id=cinder-backup-sys source-dir=/sys target-dir=/sys options=rw storage-map id=cinder-backup-lib-modules source-dir=/lib/modules target-dir=/lib/modules options=ro storage-map id=cinder-backup-var-lib-cinder source-dir=/var/lib/cinder target-dir=/var/lib/cinder options=z storage-map id=cinder-backup-var-lib-iscsi source-dir=/var/lib/iscsi target-dir=/var/lib/iscsi options=z --disabled failed: . Too many tries", "Error: /Stage[main]/Tripleo::Profile::Pacemaker::Cinder::Backup_bundle/Pacemaker::Resource::Bundle[openstack-cinder-backup]/Pcmk_bundle[openstack-cinder-backup]/ensure: change from 'absent' to 'present' failed: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20240301-171368-id3kis resource bundle create openstack-cinder-backup container podman image=cluster.common.tag/cinder-backup:pcmklatest replicas=1 options=\"--ipc=host --privileged=true --user=root --log-driver=k8s-file --log-opt path=/var/log/containers/stdouts/openstack-cinder-backup.log -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\" run-command=\"/bin/bash /usr/local/bin/kolla_start\" network=host storage-map id=cinder-backup-etc-hosts source-dir=/etc/hosts target-dir=/etc/hosts options=ro storage-map id=cinder-backup-etc-localtime source-dir=/etc/localtime target-dir=/etc/localtime options=ro storage-map id=cinder-backup-etc-pki-ca-trust-extracted source-dir=/etc/pki/ca-trust/extracted target-dir=/etc/pki/ca-trust/extracted options=ro storage-map id=cinder-backup-etc-pki-ca-trust-source-anchors source-dir=/etc/pki/ca-trust/source/anchors target-dir=/etc/pki/ca-trust/source/anchors options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.crt source-dir=/etc/pki/tls/certs/ca-bundle.crt target-dir=/etc/pki/tls/certs/ca-bundle.crt options=ro storage-map id=cinder-backup-etc-pki-tls-certs-ca-bundle.trust.crt source-dir=/etc/pki/tls/certs/ca-bundle.trust.crt target-dir=/etc/pki/tls/certs/ca-bundle.trust.crt options=ro storage-map id=cinder-backup-etc-pki-tls-cert.pem source-dir=/etc/pki/tls/cert.pem target-dir=/etc/pki/tls/cert.pem options=ro storage-map id=cinder-backup-dev-log source-dir=/dev/log target-dir=/dev/log options=rw storage-map id=cinder-backup-etc-puppet source-dir=/etc/puppet target-dir=/etc/puppet options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-cinder source-dir=/var/lib/config-data/puppet-generated/cinder target-dir=/var/lib/kolla/config_files/src options=ro storage-map id=cinder-backup-var-log-containers-cinder source-dir=/var/log/containers/cinder target-dir=/var/log/cinder options=z storage-map id=cinder-backup-var-lib-kolla-config_files-cinder_backup.json source-dir=/var/lib/kolla/config_files/cinder_backup.json target-dir=/var/lib/kolla/config_files/config.json options=ro storage-map id=cinder-backup-var-lib-config-data-puppet-generated-iscsid-etc-iscsi source-dir=/var/lib/config-data/puppet-generated/iscsid/etc/iscsi target-dir=/var/lib/kolla/config_files/src-iscsid options=ro storage-map id=cinder-backup-var-lib-tripleo-config-ceph source-dir=/var/lib/tripleo-config/ceph target-dir=/var/lib/kolla/config_files/src-ceph options=z storage-map id=cinder-backup-dev source-dir=/dev target-dir=/dev options=rw storage-map id=cinder-backup-run source-dir=/run target-dir=/run options=rw storage-map id=cinder-backup-sys source-dir=/sys target-dir=/sys options=rw storage-map id=cinder-backup-lib-modules source-dir=/lib/modules target-dir=/lib/modules options=ro storage-map id=cinder-backup-var-lib-cinder source-dir=/var/lib/cinder target-dir=/var/lib/cinder options=z storage-map id=cinder-backup-var-lib-iscsi source-dir=/var/lib/iscsi target-dir=/var/lib/iscsi options=z --disabled failed: . Too many tries"], "stdout": "Notice: Compiled catalog for standalone.localdomain in environment production in 1.29 seconds\nNotice: /Stage[main]/Tripleo::Profile::Pacemaker::Cinder::Backup_bundle/Pacemaker::Property[cinder-backup-role-standalone]/Pcmk_property[property-standalone-cinder-backup-role]/ensure: created\nNotice: Applied catalog in 260.32 seconds\nApplication:\n   Initial environment: production\n   Converged environment: production\n         Run mode: user\nChanges:\n            Total: 1\nEvents:\n          Failure: 1\n          Success: 1\n            Total: 2\nResources:\n          Changed: 1\n           Failed: 1\n      Out of sync: 2\n          Skipped: 210\n            Total: 213\nTime:\n   Config retrieval: 1.39\n         Last run: 1709278393\n      Pcmk bundle: 252.26\n   Transaction evaluation: 260.29\n   Catalog application: 260.32\n    Pcmk property: 6.37\n            Total: 260.32\nVersion:\n           Config: 1709278131\n           Puppet: 7.10.0", "stdout_lines": ["Notice: Compiled catalog for standalone.localdomain in environment production in 1.29 seconds", "Notice: /Stage[main]/Tripleo::Profile::Pacemaker::Cinder::Backup_bundle/Pacemaker::Property[cinder-backup-role-standalone]/Pcmk_property[property-standalone-cinder-backup-role]/ensure: created", "Notice: Applied catalog in 260.32 seconds", "Application:", "   Initial environment: production", "   Converged environment: production", "         Run mode: user", "Changes:", "            Total: 1", "Events:", "          Failure: 1", "          Success: 1", "            Total: 2", "Resources:", "          Changed: 1", "           Failed: 1", "      Out of sync: 2", "          Skipped: 210", "            Total: 213", "Time:", "   Config retrieval: 1.39", "         Last run: 1709278393", "      Pcmk bundle: 252.26", "   Transaction evaluation: 260.29", "   Catalog application: 260.32", "    Pcmk property: 6.37", "            Total: 260.32", "Version:", "           Config: 1709278131", "           Puppet: 7.10.0"]}
2024-03-01 07:33:14,161 p=47059 u=root n=ansible | PLAY RECAP *********************************************************************
2024-03-01 07:33:14,163 p=47059 u=root n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
2024-03-01 07:33:14,163 p=47059 u=root n=ansible | standalone                 : ok=544  changed=263  unreachable=0    failed=1    skipped=237  rescued=0    ignored=0   
2024-03-01 07:33:14,164 p=47059 u=root n=ansible | undercloud                 : ok=160  changed=57   unreachable=0    failed=0    skipped=33   rescued=0    ignored=2   
```
https://logserver.rdoproject.org/23/723/44f04179b44f477ea80a0f685371763548b62169/github-check/cifmw-data-plane-adoption-osp-17-to-extracted-crc/86ed4da/standalone/root/ansible.log

**Comment by yadneshk** [comment]
Previous edpm failure
```
 "stdout": "error: the cert-manager CRDs are not yet installed on the Kubernetes API server", "stdout_lines": ["error: the cert-manager CRDs are not yet installed on the Kubernetes API server"]}
```

**Pull request closed without merging**
