### PR TITLE
Port zuul jobs to ci-framework

### PR DESCRIPTION
**Pull request by raukadah**
Ports the zuul jobs to ci-framework

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/251

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Pull request merged**
