### PR TITLE
Remove deployStrategy kustomization

### PR DESCRIPTION
**Pull request by rabi**

### CODE REVIEW

**Comment by rabi** [comment]
/test install-yamls-deploy

error: timed out waiting for the condition on openstackcontrolplanes/openstack-galera

**Comment by abays** [comment]
Seeing this error in the Data Plane operator logs:

```
{"level":"error","ts":"2023-09-22T07:15:46Z","msg":"Reconciler error","controller":"openstackdataplanenodeset","controllerGroup":"dataplane.openstack.org","controllerKind":"OpenStackDataPlaneNodeSet","OpenStackDataPlaneNodeSet":{"name":"openstack-edpm-ipam","namespace":"openstack"},"namespace":"openstack","name":"openstack-edpm-ipam","reconcileID":"45f84eac-2fd3-40c1-9c53-eb590cc4022c","error":"openstackdataplanenodesets.dataplane.openstack.org \"openstack-edpm-ipam\" is forbidden: User \"system:serviceaccount:openstack-operators:dataplane-operator-controller-manager\" cannot patch resource \"openstackdataplanenodesets/status\" in API group \"dataplane.openstack.org\" in the namespace \"openstack\""
```

https://review.rdoproject.org/zuul/build/6d7728d7adbe4e85b2324e67b5f286a7/log/ci-framework-data/artifacts/must-gather.local.2359472218303190313/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack-operators/pods/dataplane-operator-controller-manager-7579b4dd5d-fp8zp/logs/dataplane-operator-controller-manager-7579b4dd5d-fp8zp.log#589

**Comment by rabi** [comment]
> Seeing this error in the Data Plane operator logs:

There are are tons for errors.. But mostly to me it's down to resource constraints. Not related to the PR though. I suspect there is too much overcommit of resources with vex and that's resulting in all these weird failures.

https://logserver.rdoproject.org/46/546/4e9446484708261aa42a1b90a05ef05639e6e36b/github-check/install-yamls-crc-podified-edpm-baremetal/6d7728d/ci-framework-data/logs/crc/pods/openstack-operators_dataplane-operator-controller-manager-7579b4dd5d-fp8zp_ba70cf2d-604a-40f2-bb67-d193e6da657d/manager/1.log

Controller","controller":"openstackdataplanedeployment","controllerGroup":"dataplane.openstack.org","controllerKind":"OpenStackDataPlaneDeployment"}
2023-09-22T06:59:00.031191060+00:00 stderr F {"level":"info","ts":"2023-09-22T06:59:00Z","logger":"controllers.OpenStackDataPlaneNodeSet","msg":"Reconcile request for: [openstack/openstack-edpm-ipam]"}
2023-09-22T06:59:01.339764194+00:00 stderr F 2023/09/22 06:59:01 http: TLS handshake error from 10.217.0.25:53154: EOF
2023-09-22T06:59:02.047450768+00:00 stderr F I0922 06:59:02.043065       1 trace.go:236] Trace[2014863386]: "DeltaFIFO Pop Process" ID:openshift-marketplace/certified-operators-dockercfg-hz7fl,Depth:169,Reason:slow event handlers blocking the queue (22-Sep-2023 06:59:01.941) (total time: 101ms):
2023-09-22T06:59:02.047450768+00:00 stderr F Trace[2014863386]: [101.885136ms] [101.885136ms] END

**Review by fao89 — APPROVED** [review]

**Comment by abays** [comment]
Same `install-yamls-deploy` problem here as in #545:

```
Warning  Failed          23m (x3 over 24m)     kubelet            Failed to pull image "quay.io/infrawatch/sg-core@sha256:f277dbed6ec445a3b4707b8d3dd71d871feebb8e92ec9995d49e003c6069931d": rpc error: code = Unknown desc = reading manifest sha256:f277dbed6ec445a3b4707b8d3dd71d871feebb8e92ec9995d49e003c6069931d in quay.io/infrawatch/sg-core: manifest unknown: manifest unknown
```

**Review by slagle — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Pull request merged**
