### PR TITLE
Enable heat in standalone by default

### PR DESCRIPTION
**Pull request by rabi**
We've it enabled after adoption in jobs but not before it.

### CODE REVIEW

**Comment by rabi** [comment]
recheck https://review.rdoproject.org/r/c/rdo-jobs/+/55212 merged

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
OK, Now heat adoption is tested with the jobs using standalone. https://logserver.rdoproject.org/41/941/4cf5437c5fb6523d6acd369ec07859fb4ca638a1/github-check/adoption-standalone-to-crc-ceph-provider/bbd30cf/standalone/containers/heat/

**Review by fao89 — APPROVED** [review]

**Pull request merged**
