### PR TITLE
Add script to assist on cloning repos

### PR DESCRIPTION
**Pull request by viroel**
This patch adds a new `clone-operator-repo` script that assists on cloning operator's code. It allows user to optionally provide a commit hash to be checked out at the end.
Also, the script includes an option, called CHECKOUT_FROM_OPENSTACK_REF, that automatically retrieves the operator's reference from `openstack-operator go.mod` and checkout that specific commit hash found.
This functionality is useful when deploying control-plane and data-plane, to guarantee that the CRs used in the deploy are in sync with operators installed by the openstack-operator.
Note: CHECKOUT_FROM_OPENSTACK_REF is disabled by default for now.

### CODE REVIEW

**Comment by viroel** [comment]
/hold

under testing with CI

**Comment by viroel** [comment]
recheck

**Comment by viroel** [comment]
More tests here:
Enabling CHECKOUT_FROM_OPENSTACK_REF in ci-framework:
*  https://github.com/openstack-k8s-operators/ci-framework/pull/1177
Testing a dataplane-operator PR, to see if it gets the content from the PR instead:
* https://github.com/openstack-k8s-operators/dataplane-operator/pull/696

Clone commands are displayed in make target's logs, e.g:  _controller/ci-framework-data/logs/ci_script_010_run_edpm_deploy_prep.log_

**Review by cjeanner — COMMENTED** [review]
/lgtm

**Pull request merged**
