### PR TITLE
Add certmanager target to install via olm

### PR DESCRIPTION
**Pull request by stuggi**
Jira: [OSP-26299](https://issues.redhat.com//browse/OSP-26299)

### CODE REVIEW

**Comment by rabi** [comment]
Looks like the namespace is missing.

Error from server (NotFound): error when creating "/home/zuul/ci-framework-data/artifacts/manifests/cert-manager-operator/cert-manager/op/operatorgroup.yaml": namespaces "cert-manager-operator" not found
Error from server (NotFound): error when creating "/home/zuul/ci-framework-data/artifacts/manifests/cert-manager-operator/cert-manager/op/subscription.yaml": namespaces "cert-manager-operator" not found
gmake: *** [Makefile:1802: certmanager] Error 1

**Review by dprince — APPROVED** [review]

**Comment by stuggi** [comment]
rebased

**Comment by stuggi** [comment]
running a test on ocp 4.10 which is used by prow. maybe the `startingCSV: cert-manager-operator.v1.11.1` is not available there

**Comment by stuggi** [comment]
> running a test on ocp 4.10 which is used by prow. maybe the `startingCSV: cert-manager-operator.v1.11.1` is not available there

yes thats the issue. in OCP 4.10 cert-manager was techpreview, so there is no stable-v1 channel. will update the PR

**Comment by stuggi** [comment]
deploying cert-manager worked
```
oc apply -f /alabama/install_yamls/out/openstack-operators/namespace.yaml
namespace/openstack-operators created
sleep 2
oc project openstack-operators
Now using project "openstack-operators" on server "https://api.oko-09.oooci.ccitredhat.com:6443".
make operator_namespace
make[1]: Entering directory '/alabama/install_yamls'
bash scripts/gen-namespace.sh
+ '[' -z /alabama/install_yamls/out ']'
+ '[' -z openshift-cert-manager-operator ']'
+ OUT_DIR=/alabama/install_yamls/out/openshift-cert-manager-operator
+ '[' '!' -d /alabama/install_yamls/out/openshift-cert-manager-operator ']'
+ mkdir -p /alabama/install_yamls/out/openshift-cert-manager-operator
+ cat
oc apply -f /alabama/install_yamls/out/openshift-cert-manager-operator/namespace.yaml
namespace/openshift-cert-manager-operator created
sleep 2
oc project openshift-cert-manager-operator
Now using project "openshift-cert-manager-operator" on server "https://api.oko-09.oooci.ccitredhat.com:6443".
make[1]: Leaving directory '/alabama/install_yamls'
bash scripts/gen-olm-cert-manager.sh
+ '[' -z /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op ']'
+ '[' -z openshift-cert-manager-operator ']'
+ '[' -z 4.10 ']'
+ '[' -z tech-preview ']'
+ '[' '!' -d /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op ']'
+ mkdir -p /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op
+ echo OCP_RELEASE 4.10
OCP_RELEASE 4.10
+ echo OPERATOR_DIR /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op
OPERATOR_DIR /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op
+ echo OPERATOR_NAMESPACE openshift-cert-manager-operator
OPERATOR_NAMESPACE openshift-cert-manager-operator
+ echo CHANNEL tech-preview
CHANNEL tech-preview
+ '[' 4.10 = 4.10 ']'
+ cat
+ cat
oc apply -f /alabama/install_yamls/out/openshift-cert-manager-operator/cert-manager/op
operatorgroup.operators.coreos.com/openshift-cert-manager-operator-nd6mt created
subscription.operators.coreos.com/openshift-cert-manager-operator created
while ! (oc get pod --no-headers=true -l name=cert-manager-operator -n openshift-cert-manager-operator| grep "cert-manager-operator"); do sleep 10; done
No resources found in openshift-cert-manager-operator namespace.
No resources found in openshift-cert-manager-operator namespace.
No resources found in openshift-cert-manager-operator namespace.
No resources found in openshift-cert-manager-operator namespace.
cert-manager-operator-6b6d6985d9-8g2nf   0/1   ContainerCreating   0     1s
oc wait pod -n openshift-cert-manager-operator --for condition=Ready -l name=cert-manager-operator --timeout=300s
pod/cert-manager-operator-6b6d6985d9-8g2nf condition met
while ! (oc get pod --no-headers=true -l app=cainjector -n openshift-cert-manager | grep "cert-manager-cainjector"); do sleep 10; done
No resources found in openshift-cert-manager namespace.
cert-manager-cainjector-5bdf74d88b-hsrzl   0/1   ContainerCreating   0     7s
oc wait pod -n openshift-cert-manager -l app=cainjector --for condition=Ready --timeout=300s
pod/cert-manager-cainjector-5bdf74d88b-hsrzl condition met
while ! (oc get pod --no-headers=true -l app=webhook -n openshift-cert-manager | grep "cert-manager-webhook"); do sleep 10; done
cert-manager-webhook-78d8f6d7bb-clg8d   0/1   Running   0     10s
oc wait pod -n openshift-cert-manager -l app=webhook --for condition=Ready --timeout=300s
pod/cert-manager-webhook-78d8f6d7bb-clg8d condition met
while ! (oc get pod --no-headers=true -l app=cert-manager -n openshift-cert-manager | grep "cert-manager"); do sleep 10; done
No resources found in openshift-cert-manager namespace.
cert-manager-5bc4bc88f9-h7r4b   1/1   Running   0     7s
oc wait pod -n openshift-cert-manager -l app=cert-manager --for condition=Ready --timeout=300s
```

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
> @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/install-yamls-deploy 	[c0c887b](https://github.com/openstack-k8s-operators/install_yamls/commit/c0c887b712f61280c1cf4cf1dc916859af1e27d5) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_install_yamls/389/pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy/1679110915233943552) 	false 	`/test install-yamls-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=install_yamls&pr=389). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).

The same error has occurred over a couple retries:

```
+ sleep 10
+ '[' 28 -ge 30 ']'
+ oc get deployment openstack-operator-controller-manager
Error from server (NotFound): deployments.apps "openstack-operator-controller-manager" not found
+ n=29
+ sleep 10
+ '[' 29 -ge 30 ']'
+ oc get deployment openstack-operator-controller-manager
Error from server (NotFound): deployments.apps "openstack-operator-controller-manager" not found
+ n=30
+ sleep 10
+ '[' 30 -ge 30 ']'
++ oc get subscription openstack-operator -o 'jsonpath={.status.installedCSV}'
Error from server (NotFound): subscriptions.operators.coreos.com "openstack-operator" not found
+ INSTALLED_CSV=
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-07-12T12:29:32Z"}
error: failed to execute wrapped command: exit status 1
```

Not sure what is going on.

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
I see why CI is failing now:

```
Now using project "openstack-operators" on server "https://api.oko-08.oooci.ccitredhat.com:6443".
...
oc project openshift-cert-manager-operator
Now using project "openshift-cert-manager-operator" on server "https://api.oko-08.oooci.ccitredhat.com:6443".
```

Then it's trying to find the controller-manager pod for the OpenStack operator in that `openshift-cert-manager-operator` namespace:

```
oc get deployment openstack-operator-controller-manager
Error from server (NotFound): deployments.apps "openstack-operator-controller-manager" not found
```

This does not happen when I run this locally, so it seems to be a quirk of how the `ci/prow/install-yamls-deploy` executes it steps.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
