### PR TITLE
Create openstackdataplanedeployment CR in baremetal job

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/474

### CODE REVIEW

**Comment by fao89** [comment]
why do we have 2 `gen-edpm-baremetal-kustomize.sh`?

**Comment by rabi** [comment]
> why do we have 2 `gen-edpm-baremetal-kustomize.sh`?

because, they do different things and cater to different make targets.

1. For  `edpm_deploy_baremetal` target, when deploying baremetal nodes with IPI installed openshift that has CBO (BMHs exist in openshift-machine-api namesapce)
2. For `edpm_baremetal` target in devsetup used in CI/CRC where we creat the BMHs with kustomizations along with kustomizing dataplane CRs.

**Comment by rabi** [comment]
baremetal job would be broken in this PR till https://github.com/openstack-k8s-operators/dataplane-operator/pull/378 merges or the Depends-On there is switched.

**Comment by arxcruz** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Review by bshephar — APPROVED** [review]

**Comment by fao89** [comment]
`podified-multinode-edpm-deployment-crc` failed because it was depending on https://github.com/openstack-k8s-operators/install_yamls/pull/534

**Comment by fao89** [comment]
`install-yamls-crc-podified-edpm-baremetal ` was after successful dataplane deploy

**Pull request merged**
