### PR TITLE
edpm-compute-0 also needs an ansibleSSHPrivateKey field for local dev…

### PR DESCRIPTION
**Pull request by jlarriba**
…elopment

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by jlarriba** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Pull request merged**
