### PR TITLE
Run neutron kuttl in arbitrary namespace

### PR DESCRIPTION
**Pull request by cescgina**
Run nutron kuttl tests in arbitrary namepsace instead of the default
openstack namespace.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
> @cescgina: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/install-yamls-deploy 	[e0a69a2](https://github.com/openstack-k8s-operators/install_yamls/commit/e0a69a250b6a7eac908de30c482d60fa0403e9b1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_install_yamls/458/pull-ci-openstack-k8s-operators-install_yamls-main-install-yamls-deploy/1687100347916488704) 	false 	`/test install-yamls-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=install_yamls&pr=458). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:cescgina).

```
error: unable to create the debug pod "oko-09-6fxlj-master-0-debug"
make: *** [Makefile:404: crc_storage] Error 1
````

/test install-yamls-deploy

**Comment by cescgina** [comment]
recheck

**Comment by abays** [comment]
recheck

**Pull request merged**
