### PR TITLE
Add routes to the net-iso bridge

### PR DESCRIPTION
**Pull request by hjensas**
Add route so that the nat64 router knows where to forward fd00:aaaa::/64 traffic.

Add route on the host to ensure nat64 IPv6 prefix is routed to the nat64 router.

Use forwarding mode "open" when using IPv6 - this turns off all the Libvirt firewalling that otherwise get's in the way.

Alos remove some of the options, we use env vars to drive it.

### CODE REVIEW

**Comment by morucci** [comment]
recheck

**Review by rabi — APPROVED** [review]
/lgtm

**Comment by rabi** [comment]
recheck

**Review by rabi — APPROVED** [review]
/lgtm

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Pull request merged**
