### PR TITLE
Rely on configMap mechanism to pass OVN and Metadata configuration to EDP

### PR DESCRIPTION
**Pull request by booxter**
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/469

### CODE REVIEW

**Comment by booxter** [comment]
We should be able to merge this PR after https://github.com/openstack-k8s-operators/edpm-ansible/pull/325 lands.

**Comment by booxter** [comment]
Metadata agent is not configured to use dbAddress. Apparrently ansibleee didn't mount the Secrets from nova and neutron for the ovn service. We can see that Service definition for ovn doesn't include additional secrets here:

https://review.rdoproject.org/zuul/build/1720ed9b3df3417591c505742003f608/log/controller/ci-framework-data/logs/crc/crs/openstackdataplaneservices.yaml

Is it an old dataplane-operator?

**Comment by booxter** [comment]
Don't merge it. Apparently an older dataplane-operator is pulled in CI. We need to validate it with the latest first.

**Comment by booxter** [comment]
recheck

**Comment by booxter** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Pull request merged**
