### PR TITLE
Run ansibleee kuttl in arbitrary namespace

### PR DESCRIPTION
**Pull request by cescgina**
Run openstack-ansibleee kuttl tests in arbitrary namepsace instead
of the default openstack namespace.

### CODE REVIEW

**Review by slagle — APPROVED** [review]

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
