### PR TITLE
Revert "Revert "Add certmanager target to install via olm""

### PR DESCRIPTION
**Pull request by stuggi**
Logs did not show issues with the reverted PR, lets introduce it again.

This reverts commit 25948b750efb8d43b79298fc97a3da074cb63b96.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
```
2023-07-25 07:58:48,827 p=9767 u=zuul n=ansible | An exception occurred during task execution. To see the full
traceback, use -vvv. The error was: keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection 
to http://keystone-public-openstack.apps-crc.testing/v3/auth/tokens: ('Connection aborted.', 
RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by stuggi** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
At this point both deployment Zuul jobs have passed independently.  Will try to get both in one run one more time.

**Pull request merged**
