### PR TITLE
Use AEE v1beta1

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by abays** [comment]
recheck

Kernel panic:

```
[   65.669432] ---[ end Kernel panic - not syncing: Jitter RNG permanent health test failure ]---
```

**Comment by fao89** [comment]
recheck

**Review by slagle — COMMENTED** [review]
+2

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
