### PR TITLE
Allow CRC to learn routes through BGP

### PR DESCRIPTION
**Pull request by luis5tb**

### CODE REVIEW

**Comment by luis5tb** [comment]
recheck unrelated openstackclient pod not starting issue

**Comment by abays** [comment]
recheck

This [1] merged, which might fix the data plane adoption job

[1] https://github.com/openstack-k8s-operators/data-plane-adoption/pull/186

**Comment by luis5tb** [comment]
recheck

**Comment by luis5tb** [comment]
recheck unrelated heat error

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
